---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: tracker-resource
  path: gopath/src/github.com/concourse/tracker-resource

outputs:
- name: built-resource

params:
  TRACKER_TOKEN:
  TRACKER_PROJECT:

run:
  path: gopath/src/github.com/concourse/tracker-resource/scripts/ci
