---
image: docker:///concourse/static-golang

inputs:
  - name: tracker-resource
    path: gopath/src/github.com/concourse/tracker-resource

run:
  path: gopath/src/github.com/concourse/tracker-resource/scripts/test
